apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: voluminous-silkworm-dotnet-basic
  janus-idp.io/tekton: voluminous-silkworm-dotnet-basic
  backstage.io/kubernetes-id: voluminous-silkworm-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: voluminous-silkworm-dotnet-basic
resources: 
- deployment.yaml
- route.yaml
- service.yaml
